### PR TITLE
Create Error handling Function

### PR DESCRIPTION
**Pull request by haodev007**

### CODE REVIEW

**Comment by clintnetwork** [comment]
The check have failed, please take a look to this!

**Review by clintnetwork — CHANGES_REQUESTED** [review]
Hey,

If you can just ensure to use double quotes and not single, I will be able to merge it.

**Comment by haodev007** [comment]
Hi,
I have replaced all single quotes to double ones.
Please review and if everything is okay, merge plz.
I will try to match my code style to team one.
Thanks!

**Review by clintnetwork — APPROVED** [review]

**Comment by clintnetwork** [comment]
> Hi, I have replaced all single quotes to double ones. Please review and if everything is okay, merge plz. I will try to match my code style to team one. Thanks!

ah perfect thank you

**Pull request merged**
