### PR TITLE
Voting system

### PR DESCRIPTION
**Pull request by haodev007**

### CODE REVIEW

**Comment by clintnetwork** [comment]
Hi @haodev007,

if you can apply this changes: 
- comment line 212 of header.tsx (`<div className="w-full border-t border-white border-opacity-10" />`)
- Add a link of the IDO name in the list to IDO details page
- Replace the block “Want to launch project”  by “The Vital Concepts Behind Parasol” from tiers page (Then I will replace texts)
- Put not active IDOs in gray (like draft badge) and purple-2 for active IDOs.

**Comment by haodev007** [comment]
> Hi @haodev007,
> 
> if you can apply this changes:
> 
> * comment line 212 of header.tsx (`<div className="w-full border-t border-white border-opacity-10" />`)
> * Add a link of the IDO name in the list to IDO details page
> * Replace the block “Want to launch project”  by “The Vital Concepts Behind Parasol” from tiers page (Then I will replace texts)
> * Put not active IDOs in gray (like draft badge) and purple-2 for active IDOs.

Hi @clintnetwork 
I think we have the link of the IDO name..

**Comment by clintnetwork** [comment]
> > Hi @haodev007,
> > if you can apply this changes:
> > 
> > * comment line 212 of header.tsx (`<div className="w-full border-t border-white border-opacity-10" />`)
> > * Add a link of the IDO name in the list to IDO details page
> > * Replace the block “Want to launch project”  by “The Vital Concepts Behind Parasol” from tiers page (Then I will replace texts)
> > * Put not active IDOs in gray (like draft badge) and purple-2 for active IDOs.
> 
> Hi @clintnetwork I think we have the link of the IDO name..

Nope not clickable on my side.

Screenshot 2022-05-29 at 20 34 10

**Comment by haodev007** [comment]
> > > Hi @haodev007,
> > > if you can apply this changes:
> > > 
> > > * comment line 212 of header.tsx (`<div className="w-full border-t border-white border-opacity-10" />`)
> > > * Add a link of the IDO name in the list to IDO details page
> > > * Replace the block “Want to launch project”  by “The Vital Concepts Behind Parasol” from tiers page (Then I will replace texts)
> > > * Put not active IDOs in gray (like draft badge) and purple-2 for active IDOs.
> > 
> > 
> > Hi @clintnetwork I think we have the link of the IDO name..
> 
> Nope not clickable on my side.
> 
> Screenshot 2022-05-29 at 20 34 10

Ohh, I misunderstood you. I will add it.

**Comment by haodev007** [comment]
Hi @clintnetwork 
May I reset max decimal based on Solana one(9)?

**Comment by clintnetwork** [comment]
Hello @haodev007, I think you are mistaken.

I want to put the same text on the voting page than tiers page, and then update it, because the "Want to launch a project" is not relevant in the voting page, better explain to people how voting works!

Screenshot 2022-05-30 at 14 39 45

**Comment by haodev007** [comment]
Hi @clintnetwork
I have put the text like this on tiers and voting page like this
- voting page
image
- tiers page
image

**Pull request merged**
